[package]
name = "zk-bootcamp"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.5.0"
ark-ff = "0.5.0"
ark-std = "0.5.0"
criterion = { version = "0.5.1", features = ["html_reports"] }
rand = "0.8.5"

[[bench]]
name = "multilinear_poly_benchmark"
harness = false
