[package]
name = "zk-bootcamp"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.5.0"
ark-ff = "0.5.0"
ark-std = "0.5.0"
dusk-bls12_381 = "0.13.0"
dusk-poseidon = "0.40.0"
rand = "0.8.5"
