[package]
name = "sum_check"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.5.0"
fiat_shamir ={ path = "../fiat_shamir"}
multilinear_polynomial ={ path = "../multilinear_polynomial"}